sudo: required
services:
- docker
env:
  global:
    secure: 25GIWdojNCP9k8ocViyKkeNqZ8hqomDgNjuGni/5FSq1YcK+JJaCzTm3TtZMiWM5csm7Eoe5HtXW1vqgJipDCMuu23l+Ck9HO8Q0iQyivr+k76RdZHjm/7jX+766lGI96uBc66kECz/8E/JaH74QbUCneULiQ46mJZlYvaXssOKdTTFw2nbczDB7ql7NpRrLR65eaD4beIibDnw2iYSiXvtohiu3xABPYQ39G1yQYHG1c+JlmBwThU835sPdgG+i3Bv8jqbX6MXPl2DpFzQtVVP+lkVSElguGsWE2dBjeFRyP6ll5xXXxN9asTzuir4iPGI/dEw8tcLQNbF3+xPI8Lfa7AcoU4cXKzx/Gfb5hUO43b+YzptIIzjwZopKFl0haRkUIPhEN2vElC0Rf/uOET4KSYnYqotI/6xtw/rftF1e99koQgbEJpC5mFabjYNoVFmxjPo49ExM6v2wjPNuG7SF/Ux3CjIrxkPDHqcwsd7Fb0uCbZEKK/ukVMCKo1zh3ETEN/wGiS7CM9lxIya6sv0pKioOBWd7KcD0bhCIn6sK2n1APzHo+qbFT6m8COkFdbgPmZrPs+V0XiJPKuJAKpx66NfNuB19ImeElgYFTCB5S0Oj0ozC/rV4PQTMljx/smgdfmcTmB/6A79VLOnIoufEQOVjenPUtQ9ODCnIEbs=
notifications:
  slack: houseofdota:nPHDCErAqwuYyOy9RXzmsgwS
language: generic
before_install:
- mkdir /opt/houseofdota
- touch /opt/houseofdota/.env
before_script:
- docker-compose build
script:
- docker-compose -p houseofdota_tests up --abort-on-container-exit python_unit_tests
- docker-compose -p houseofdota_tests up --abort-on-container-exit js_unit_tests
before_deploy: docker-compose -p houseofdota_tests down
deploy:
  provider: heroku
  api_key:
    secure: NdX+91KhTOkFGqIU0RyYOGFoU9Q292uHbIrNdFwq3QDE+EK8rVDJnbHm252fzx1mo52qvb6KG62OdMGXIHQpnPFvTjUY3SCQcvvakHWlsX1Iub8XJoB7d3uSLDGOsNlj988rxq+ssf1B3lDhKfX0SKXVQNInFHni9Kb6om2OE+d4a1oPhNyF8Y+ByrZC98gO1b1+o46N4KlwrdwIkIZwkXZBa1RXn7MlfSFL+M5I7f0PpKiZb5EbhAZilflk/IiRbsZ08FT0av9p3GSkWexJ8vtCP7RZk7zsrROQeuqKqxo76073oDStydrI6/0zhFAiEJ6A1RzO+UmPQANzM5fmVA/b7biJYw6Wrs9vlFYV2C8IFtP5k0dHnbjeYr2mHOLHPdjGvuus0BrbFiIDjPt32RizYHAgt+Ssxg2/CySWI5qY3lC13+r7zMVcFKcXYaPEy8akW+te0ILY6m/6vWszkT1hW+5w+Zgc5sRUJElVH2dPDhkmRrp3HvsQx8TFnEpv5et6e14msM3L4gjkU3E6e6NfQmySvzEd6XGpIUVgFU4uTCcsOXdNN/CQum23KgDLnbkgAixCkva2wIc0cYENeBf89dC6oG8zctm0voKAWFhOtHzfR9Tc6fLAUUbR4qIpS68EYv/raplgta9C0V0+Xtko+QyltBOg8YY+bEnwRDk=
after_deploy:
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
- chmod a+x /tmp/travis-automerge
- BRANCHES_TO_MERGE_REGEX='^master$' BRANCH_TO_MERGE_INTO=master-beatworker GITHUB_REPO=lucashanke/houseofdota /tmp/travis-automerge
