version: '2.1'

services:

  base:
    image: houseofdota:base
    build:
      context: .
    env_file:
      - .env

  app:
    image: houseofdota:app
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env
    depends_on:
      - base

  redis:
    image: redis
    ports:
      - 6379:6379
    build:
      context: .
      dockerfile: Dockerfile.redis

  beat:
    image: houseofdota:base
    command: ["celery", "-A", "houseofdota", "beat"]
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - base
    restart: always

  worker:
    image: houseofdota:base
    command: ["celery", "-A", "houseofdota", "worker", "-l", "debug", "--autoscale=5,3"]
    volumes:
      - ./opt/houseofdota/files/nn:/usr/src/houseofdota/files/nn/
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - base
    restart: always

  database:
    image: database
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5431:5432
    healthcheck:
      test: "exit 0"

  app_test:
    image: houseofdota:base
    command: ["./manage.py", "test"]
    environment:
      - DJANGO_SETTINGS_MODULE=houseofdota.settings
      - DATABASE_NAME=houseofdota
      - DATABASE_USER=hoduser_test
      - DATABASE_PASSWORD=hod123
      - DATABASE_HOST=database
      - DATABASE_PORT=5431
    volumes:
      - /opt/houseofdota/files:/usr/src/houseofdota/files
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
