# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 00:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('match_seq_num', models.BigIntegerField(null=True)),
                ('radiant_win', models.BooleanField()),
                ('duration', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('patch', models.CharField(max_length=255, null=True)),
                ('tower_status_radiant', models.IntegerField(null=True)),
                ('tower_status_dire', models.IntegerField(null=True)),
                ('barracks_status_radiant', models.IntegerField(null=True)),
                ('barracks_status_dire', models.IntegerField(null=True)),
                ('cluster', models.IntegerField(null=True)),
                ('first_blood_time', models.IntegerField(null=True)),
                ('lobby_type', models.CharField(max_length=255, null=True)),
                ('human_players', models.IntegerField(null=True)),
                ('leagueid', models.IntegerField(null=True)),
                ('game_mode', models.CharField(max_length=255, null=True)),
                ('flags', models.IntegerField(null=True)),
                ('engine', models.IntegerField(null=True)),
                ('radiant_score', models.IntegerField(null=True)),
                ('dire_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('account_id', models.BigIntegerField(null=True)),
                ('hero_id', models.IntegerField()),
                ('items', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('kills', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('leaver_status', models.IntegerField(null=True)),
                ('last_hits', models.IntegerField(null=True)),
                ('denies', models.IntegerField(null=True)),
                ('gpm', models.IntegerField(null=True)),
                ('xpm', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('gold', models.IntegerField(null=True)),
                ('gold_spent', models.IntegerField(null=True)),
                ('hero_damage', models.IntegerField(null=True)),
                ('tower_damage', models.IntegerField(null=True)),
                ('hero_healing', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.Match')),
            ],
        ),
    ]
