# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('match_seq_num', models.BigIntegerField()),
                ('radiant_win', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('patch', models.CharField(max_length=255)),
                ('tower_status_radiant', models.IntegerField()),
                ('tower_status_dire', models.IntegerField()),
                ('barracks_status_radiant', models.IntegerField()),
                ('barracks_status_dire', models.IntegerField()),
                ('cluster', models.IntegerField()),
                ('first_blood_time', models.IntegerField()),
                ('lobby_type', models.CharField(max_length=255)),
                ('human_players', models.IntegerField()),
                ('leagueid', models.IntegerField()),
                ('game_mode', models.CharField(max_length=255)),
                ('flags', models.IntegerField()),
                ('engine', models.IntegerField()),
                ('radiant_score', models.IntegerField()),
                ('dire_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=10)),
                ('account_id', models.BigIntegerField()),
                ('hero_id', models.IntegerField()),
                ('items', models.CommaSeparatedIntegerField(max_length=6)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('leaver_status', models.IntegerField()),
                ('last_hits', models.IntegerField()),
                ('denies', models.IntegerField()),
                ('gpm', models.IntegerField()),
                ('xpm', models.IntegerField()),
                ('level', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('gold_spent', models.IntegerField()),
                ('hero_damage', models.IntegerField()),
                ('tower_damage', models.IntegerField()),
                ('hero_healing', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match')),
            ],
        ),
    ]
