# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 17:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160731_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='NnTrainingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('training_matches', models.BigIntegerField()),
                ('testing_matches', models.BigIntegerField()),
                ('training_accuracy', models.FloatField()),
                ('testing_accuracy', models.FloatField()),
                ('radiant_win_test_percentage', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='slot',
            name='items',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
