# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160815_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('version', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
