# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='app.Patch'),
        ),
        migrations.AlterField(
            model_name='nntrainingresult',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nn_results', to='app.Patch'),
        ),
    ]
