# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160827_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroesStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_combination', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('matches_played', models.BigIntegerField()),
                ('pick_rate', models.FloatField()),
                ('matches_won', models.BigIntegerField()),
                ('win_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PatchStatistics',
            fields=[
                ('patch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='statistics', serialize=False, to='app.Patch')),
                ('match_quantity', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='analysed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heroesstatistics',
            name='patch_statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heroes_statistics', to='app.PatchStatistics'),
        ),
    ]
