# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160828_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroesstatistics',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='heroesstatistics',
            name='matches_won',
        ),
        migrations.AddField(
            model_name='heroesstatistics',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='heroesstatistics',
            name='pick_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='heroesstatistics',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
