# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160903_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroesstatistics',
            name='counter_pick',
            field=models.BooleanField(default=False),
        ),
    ]
