# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160905_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroesStatistics',
            new_name='BundleAssociationRules',
        ),
    ]
