# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170703_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CounterStatistics',
            new_name='CounterAssociationRules',
        ),
    ]
