# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170703_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleassociationrules',
            name='patch_statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_rules', to='app.PatchStatistics'),
        ),
        migrations.AlterField(
            model_name='counterassociationrules',
            name='patch_statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counter_rules', to='app.PatchStatistics'),
        ),
    ]
