# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pickassociationrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='skill',
            field=models.IntegerField(default=3),
        ),
    ]
